services:
  # Web Service
  - type: web
    name: brandmantra
    env: docker
    repo: https://github.com/jarvishiv62/Brand_Mantra.git
    rootDir: .
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://brandmantra.onrender.com
      - key: DB_HOST
        value: brandmantra-db
      - key: DB_DATABASE
        value: brandmantra
      - key: DB_USERNAME
        value: brandmantra
        fromDatabase:
          name: brandmantra-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: brandmantra-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: brandmantra-db
    databaseName: brandmantra
    plan: free
